name: Compile

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install G++
      run: |
        sudo apt-get update
        sudo apt-get install g++
    - name: Compile
      run: bash compile.sh
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: brainfuck-interpreter
        path: out/brainfuck-interpreter
